function throwErrorFunc(message) {
    throw { message: message };
}
throwErrorFunc("There's an error");
